### ISSUE TITLE
Refreshing checked property

### ISSUE THREAD

**Issue by AdyStudios** [felixhao28/node-systray#11]
I couldn't find a way to simply refresh the checked property of an item.
Is there way to refresh without restarting?

**Comment by open-e-id** [comment]
I'm also looking for this feature; not just the checked state but any item.
Looking at the code, it has something to do with sendAction function.
Can @felixhao28 write some documentation about it?

**Comment by open-e-id** [comment]
Got it ! 😄 

To update an item, call `systray.sendAction({type: 'update-item', item: action.item});`

```
systray.onClick(action => {
  if (action.item.click != null) {
    action.item.click(action)
  }
})
```

```
{
  title: 'Toggle item',
  enabled: true,
  checked: false,
  click: function(action) {
    action.item.checked = !action.item.checked;
    systray.sendAction({type: 'update-item', item: action.item});
  }
}
```
