### ISSUE TITLE
missing librairie: libappindicator3.so.1

### ISSUE THREAD

**Issue by little-evil-thing** [felixhao28/node-systray#13]
I have tested systray2 on windows, and everything worked well.
But when I tested it on debian 11 with kde plasma, the module didn't worked.

Firstly the `systray.ready()` didn't resolved nor rejected, which was strange. 
I was expecting it was the binary, so I run it myself from my terminal, and got this error: 
```bash
./tray_linux: error while loading shared libraries: libappindicator3.so.1: cannot open shared object file: No such file or directory
```
On debian 11 libappindicator was removed because it is deprecated, but is still used by  many desktop applications, such as discord, while another shared librairie `libayatana-appindicator` is curently used by debian 11

(btw sorry for my poor english)

**Comment by little-evil-thing** [comment]
solution: build the binary yourself, in debian 11 environment, with the gtk3+ dev lib installed (`sudo apt-get install gcc libgtk-3-dev libayatana-appindicator3-dev`).

here are the steps:
- run `git clone https://github.com/felixhao28/systray-portable`.
- go inside the `systray-portable` folder.
- modify the `go.mod` file by changing the `require github.com/getlantern/systray v1.1.0` by `require github.com/getlantern/systray v1.2.1` (v1.1.0 => v1.2.1).
- simply run `go build`.
- then copy the `systray-portable` binary and move it in your binary folder (default : `node_modules/systray2/traybin`, named as `tray_linux_release`).

[here](https://github.com/felixhao28/node-systray/files/8826155/tray_linux.zip) is the binary, using `libayatana-appindicator` lib, for anyone lazy (even if the steps are easy).
(if you encounter any bugs with the binary, just build it yourself, it's easier)

**Comment by felixhao28** [comment]
Note to myself, add this information to a FAQ page.
