### ISSUE TITLE
Icon still appearing after process closed

### ISSUE THREAD

**Issue by Lucky38i** [felixhao28/node-systray#14]
The icon remains in the taskbar even though the process has been closed then immediately disappears if I hover my mouse over it. 

It was originally minor but if the application is opened and closed multiple time then you end up with like 10 icons in the taskbar until you mouse over it.

**Comment by felixhao28** [comment]
If you properly use `kill` method before exiting, the icon should disappear.

The definition: https://github.com/felixhao28/node-systray/blob/master/index.ts#L348

**Comment by felixhao28** [comment]
I am closing it for now. If this issue still haunts you after trying properly calling the kill method, feel free to reopen it.
