### ISSUE TITLE
Feature request : add/delete item

### ISSUE THREAD

**Issue by ghost** [felixhao28/node-systray#15]
This feature request depends on the following issue : https://github.com/felixhao28/systray-portable/issues/4

In the meantime, if found a way to make a dynamic menu by creating many (99) hidden entries and sub-entries and show/hide & update them using sendAction.

**Comment by felixhao28** [comment]
The upstream project https://github.com/getlantern/systray does not provide a way to delete a menuItem dynamically.  Therefore, the current best solution is to show/hide the items. And that's exactly what I am doing in my other projects.
