### ISSUE TITLE
ENOENT tray_windows_release.exe

### ISSUE THREAD

**Issue by Llorx** [felixhao28/node-systray#2]
Just done a `npm install systray2` and changed the `import systray from systray` to `import systray from systray2` and this error happens: `ENOENT tray_windows_release.exe`.

**Comment by felixhao28** [comment]
You need to copy the `tray_windows_release.exe` from `node_modules\systray2\traybin\tray_windows_release.exe` to `<working directory>\traybin\tray_windows_release.exe`. It was previously in `systray` `<working directory>\..\traybin\tray_windows_release.exe` which I found very strange.

**Comment by felixhao28** [comment]
I know the problem. I forgot to change the export path in the package. Let me fix it.

**Comment by felixhao28** [comment]
It should be fixed in 2.0.5.

**Comment by Llorx** [comment]
Yay, thank you.
