### ISSUE TITLE
Add support for dividers

### ISSUE THREAD

**Issue by Timeraa** [felixhao28/node-systray#3]
Hey there!

Since the original author doesn't update their module anymore and you seem to be updating it, I've come here in hope to use it for my application [PreMiD](https://premid.app/). It seems to do the trick for my use cases BUT I'd love to see the possibility to use the dividers as the go module seems to support them but this one "lacks?" them.

~ Florian

**Comment by felixhao28** [comment]
The separator support is just added (not published yet). Will you try `npm i felixhao28/node-systray` and add an "SysTray.separator" in the `menu` array and see if it works for you?

**Comment by Timeraa** [comment]
👌 Works fine but couldn't install it the proper way, it just had empty folders but locally compiling the files and testing, it works.

**Comment by Timeraa** [comment]
Also the go library seems to support sub-menus? If so that would be useful to have support for as well

**Comment by felixhao28** [comment]
Yeah installing from GitHub won't actually work because I don't commit the compiled js file to the repository.

**Comment by felixhao28** [comment]
Sub-menus support has been added to the master branch. You can pull and try again. I only tested on Windows.
