### ISSUE TITLE
No icon displayed if node run as service

### ISSUE THREAD

**Issue by si458** [felixhao28/node-systray#7]
Im having an issue with the systray2 which doesn't display the icon in the taskbar if node is running as a service using winsw or node-windows
I get the systray ready message in the windows event logs and also console logs and I can even see the systray exe being run and running too but no icon is ever displayed?

**Comment by felixhao28** [comment]
It sounds like an upstream issue. How about trying the binary from https://github.com/getlantern/systray directly as a service? And see if the icon appear?

**Comment by si458** [comment]
@felixhao28 im not sure how to build it as an exe? ive tried a few times to no luck 👎

**Comment by felixhao28** [comment]
https://github.com/getlantern/systray#try-the-example-app

![image](https://user-images.githubusercontent.com/2417391/122015160-6e39e600-cdf2-11eb-90e3-e9cdab1fa528.png)

**Comment by felixhao28** [comment]
I have an already-built binary but Github won't allow me to put it here.

**Comment by si458** [comment]
@felixhao28 ok managed to build the example, however that also doesnt work either as a service, so im guessing its something to do with running tray icons as a service maybe?

**Comment by felixhao28** [comment]
I did some google search and it seems like normally Windows services don't have access to GUI because they need to run before the user's logging in. Someone suggests using a separate process to show the tray icon.

https://social.msdn.microsoft.com/Forums/vstudio/en-US/fe24bf89-798e-43e6-a57d-9bda0ca419ff/how-to-make-a-windows-service-that-has-a-task-tray-icon-for-managing-it?forum=csharpgeneral

**Comment by si458** [comment]
@felixhao28 thats a bummer/pain
altho the node-systray does run the tray.exe seperately? (checked with procexp64.exe)
maybe you could run the exe as the currently logged in console user as it currently runs as the service user?

**Comment by salamanca2D** [comment]
I compiled mi node app with pkg and then I made an installer with advance installer, that let me execute on startup system (as a service)

**Comment by si458** [comment]
@salamanca2D do you have an example as i tried that and never got it work!

**Comment by si458** [comment]
I'm closing this as it's already discussed you can't run a tray icon in a windows service
So you must create a separate app that runs as a user instead and show the tray icon

**Comment by open-e-id** [comment]
https://www.coretechnologies.com/blog/windows-services/interact-with-desktop/
