### ISSUE TITLE
Not work win 8.1

### ISSUE THREAD

**Issue by salamanca2D** [felixhao28/node-systray#8]
Someone did tests or does it happen that the task tray does not display in windows 8.1? ;-;

**Comment by felixhao28** [comment]
Unfortunately, I don't possess a Win 8.1 computer nor do I expect to own one sometime soon. Maybe you can take a look at https://github.com/getlantern/systray and see this upstream project works on Win 8.1 or not?

**Comment by salamanca2D** [comment]
I was testing with virtualbox, I'll try the repo you mention

**Comment by open-e-id** [comment]
As a reminder, Windows 8.1 will reach the end of support on January 10, 2023 😉

**Comment by salamanca2D** [comment]
@open-e-id  I know but many small companies use it on their equipment and refuse to renew 😂

**Comment by felixhao28** [comment]
I am closing it for now since the person has deleted their account. If anyone is able to provide more information about the compatibility of the upstream [systray](https://github.com/getlantern/systray) project on Win8.1, feel free to comment, or reopen the issue if needed.
