### ISSUE TITLE
Property 'click' does not exist on type 'MenuItem'.

### ISSUE THREAD

**Issue by eNepper** [felixhao28/node-systray#9]
When I tried compile the sample from the readme I got this `error TS2339: Property 'click' does not exist on type 'MenuItem'.`
Could the click property not be added as an optional property to the MenuItem interface?

**Comment by cmidgley** [comment]
To be complete, you likely want to also extend 'items':

```
interface MenuItemClickable extends MenuItem {
	click?: () => void;
	items?: MenuItemClickable[];
}
```

**Comment by felixhao28** [comment]
I updated the readme, hoping to make it clearer for users in the future.
